from __future__ import annotations

import uuid

from ..providers.base import ToolCall
from .base import MemorySystem

# Prompts and schemas sourced from github.com/rcarroll/memory-hub.
# System prompt: memoryhub-cli/src/memoryhub_cli/project_config.py
#   — _UNIVERSAL_HEADER + _UNIVERSAL_PATTERN_BLOCKS["lazy"] + _HYGIENE_BLOCK
#   These are the generated agent instructions MemoryHub produces when a user
#   runs `memoryhub config init` with the "lazy" loading pattern (the default
#   for focused sessions).
# Tool schema: memory-hub-mcp/src/tools/memory.py
#   — the unified memory(action=...) dispatcher with full docstring
# Write response format: memory-hub-mcp/src/tools/write_memory.py
#   — the curation-aware response with memory node + curation metadata

PROMPT_SOURCE = "memoryhub-cli/src/memoryhub_cli/project_config.py"
TOOL_SCHEMA_SOURCE = "memory-hub-mcp/src/tools/memory.py"

# The MemoryHub MCP server does not inject its own system prompt. Instructions
# are generated by `memoryhub config init` and placed in the agent's rule
# files (e.g. .claude/rules/memoryhub-loading.md). This is the universal
# (framework-agnostic) lazy-loading pattern — the simplest and most common
# configuration — assembled from the template blocks in project_config.py.
SYSTEM_PROMPT = """\
# MemoryHub Agent Instructions: Lazy

This project uses MemoryHub for persistent, centralized agent memory across
conversations. You MUST use it.

## At session start

If your agent framework pre-loads memory context at startup, use it as
your working set. Otherwise, follow the manual flow below.

Authenticate with `register_session(api_key=<your_key>)`, then wait until
the user states a task or question with enough detail to form a meaningful
search query. Derive a 1-2 sentence summary and call
`search_memory(query=<summary>)`. If the opening turn is low-signal
("hi", "can you help me?"), do not search yet -- wait for a follow-up
that reveals the topic.

## During the session

- Trust your working set. Re-search only when the user explicitly
  references a concept you don't have loaded.

## Memory hygiene

- Keep memories concise and self-contained. Another agent should
  understand them without re-loading the conversation that produced them.
- DO write preferences, decisions, architectural choices, tool
  configuration, and workflow patterns. Skip ephemeral things like "user
  asked me to read a file."
- Use `update_memory` (not `write_memory`) to revise an existing entry —
  this preserves version history. Use `write_memory` only for new facts.
- Set weights deliberately: `1.0` for critical policies, `0.8-0.9` for
  strong preferences, `0.5-0.7` for nice-to-know context.
- Add rationale branches via `parent_id` + `branch_type="rationale"` when
  the "why" behind a preference is load-bearing.
- Use the right scope: `user` for personal preferences, `project` for
  project-specific context, `organizational` for team/org patterns,
  `enterprise` for mandated policies."""

# The unified memory tool schema from memory-hub-mcp/src/tools/memory.py.
# MemoryHub consolidates all operations into a single tool with an `action`
# parameter — the LLM must figure out that action="write" with content=...
# is how to persist a memory. This tests whether complex unified tool
# interfaces help or hinder proactive judgment compared to simpler schemas.
MEMORY_TOOL = {
    "name": "memory",
    "description": (
        "All-in-one memory operations. "
        "\n\nRead actions:"
        "\n  search(query, [scope, project_id, options: max_results, focus, domains, ...])"
        "\n    Semantic search. Returns cache-optimized stable ordering by default."
        "\n  list([scope, project_id, options: max_results, cursor, include_branches])"
        "\n    Enumerate memories without semantic ranking."
        "\n  read(memory_id, [project_id, options: include_versions, hydrate])"
        "\n    Retrieve memory by UUID with optional version history."
        "\n  similar(memory_id, [project_id, options: threshold, max_results])"
        "\n    Near-duplicate detection by cosine similarity."
        "\n  relationships(memory_id, [project_id, options: direction, include_provenance])"
        "\n    Query graph edges for a memory node."
        "\n  status()"
        "\n    Session identity, scopes, project memberships."
        "\n\nWrite actions:"
        "\n  write(content, [scope, project_id, options: weight, parent_id, branch_type, ...])"
        "\n    Create memory node or branch. scope defaults to 'user' if omitted."
        "\n  update(memory_id, [content, options: weight, metadata, domains])"
        "\n    New version with a new UUID; old version preserved with is_current=false."
        "\n  delete(memory_id, [project_id])"
        "\n    Soft-delete with cascade."
        "\n  report(memory_id, options: {observed_behavior})"
        "\n    Flag contradiction against a stored memory."
        "\n  resolve(options: {contradiction_id, resolution_action})"
        "\n    Close contradiction: accept_new|keep_old|mark_both_invalid|manual_merge."
        "\n\nParams in () are top-level. {braces} in options = required for that action."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "description": (
                    "The operation to perform: search, list, read, similar, "
                    "relationships, status, write, update, delete, report, resolve."
                ),
            },
            "memory_id": {
                "type": "string",
                "description": (
                    "UUID of target memory. Required for: read, update, delete, "
                    "similar, relationships, report."
                ),
            },
            "query": {
                "type": "string",
                "description": "Natural language search text. Required for: search.",
            },
            "content": {
                "type": "string",
                "description": (
                    "Memory text. Required for: write. Optional for: update."
                ),
            },
            "scope": {
                "type": "string",
                "description": (
                    "Scope: user, project, campaign, role, organizational, enterprise. "
                    "Required for: write. Optional filter for: search."
                ),
            },
            "project_id": {
                "type": "string",
                "description": (
                    "Project identifier. Required for: write (project/campaign scope), "
                    "set_focus, focus_history."
                ),
            },
            "options": {
                "type": "object",
                "description": (
                    "Action-specific parameters. For write: weight (0.0-1.0, "
                    "default 0.7), parent_id (UUID for branching), branch_type "
                    "(rationale/provenance/description/evidence), domains "
                    "(knowledge domain tags), content_type "
                    "(experiential/declarative/behavioral), relevant_until "
                    "(ISO 8601 timestamp for semantic expiry), force (bypass "
                    "near-duplicate gates)."
                ),
            },
        },
        "required": ["action"],
    },
}


class MemoryHubMemorySystem(MemorySystem):
    name = "memoryhub"
    description = (
        "MemoryHub unified memory(action=...) interface with scoped writes, "
        "weighted memories, and content type classification"
    )

    def system_prompt(self) -> str:
        return SYSTEM_PROMPT

    def tool_definitions(self) -> list[dict]:
        return [MEMORY_TOOL]

    def extract_stored_fact(self, tool_call: ToolCall) -> str:
        if tool_call.name == "memory":
            action = tool_call.arguments.get("action", "")
            if action == "write":
                return tool_call.arguments.get("content", "")
        return ""

    def format_tool_result(self, tool_call: ToolCall) -> dict:
        if tool_call.name != "memory":
            return {"status": "ok"}

        action = tool_call.arguments.get("action", "")

        if action == "write":
            memory_id = str(uuid.uuid4())
            content = tool_call.arguments.get("content", "")
            stub = content[:80] + ("..." if len(content) > 80 else "")
            return {
                "memory": {
                    "id": memory_id,
                    "content": content,
                    "stub": stub,
                    "scope": tool_call.arguments.get("scope", "user"),
                    "weight": (
                        tool_call.arguments.get("options", {}).get("weight", 0.7)
                        if isinstance(tool_call.arguments.get("options"), dict)
                        else 0.7
                    ),
                    "content_type": "experiential",
                    "is_current": True,
                    "created_at": "2026-01-01T00:00:00Z",
                },
                "curation": {
                    "blocked": False,
                    "similar_count": 0,
                    "nearest_id": None,
                    "nearest_score": None,
                    "flags": [],
                },
            }

        if action == "search":
            return {"memories": [], "total": 0}

        if action == "read":
            return {"error": "Memory not found"}

        if action == "status":
            return {
                "session_id": "bench-session",
                "user_id": "bench-user",
                "scopes": ["user"],
            }

        return {"status": "ok"}

    def version_info(self) -> dict:
        return {
            "system": self.name,
            "prompt_source": f"github.com/rcarroll/memory-hub {PROMPT_SOURCE}",
            "tool_schema_source": f"github.com/rcarroll/memory-hub {TOOL_SCHEMA_SOURCE}",
        }
